Views
isaacpitwa/ruby-blog pull request #6
Opened 2022-09-22 22:11 UTC by isaacpitwa

2022-09-22 23:10 UTC, rloterh reviewed
Hi Isaac, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a Pull Request description. Kindly ensure to add short summaries describing introduced changes in more detail of your Pull Request, and request for another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit.

2022-09-23 16:42 UTC, mateo951 requested changes
### Hi @isaacpitwa, 

**🔥Highlights🔥**
- App functionality 🐐

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-09-23 16:42 UTC, mateo951 commented on app/controllers/users_controller.rb
>    end
Users controller `#index` action renders all users to its corresponding Views index page 🔥

2022-09-23 16:42 UTC, mateo951 commented on app/controllers/users_controller.rb
> +    @most_recent_three_posts = @user.most_recent_three_posts
Uses `#recent_post` method to render the user's 3 most recent post 🤓 Well done!

2022-09-23 16:42 UTC, mateo951 commented on app/views/posts/index.html.erb
> +      <%end%>
Please be sure to use `post.recent_comments` to render 5 most recent comments in the `app/views/posts/index.html.erb` page as it is part of the requirements 📝 You already have the proper method to achieve this 🤓 The most_recent_five_comments on post model file 💪

2022-09-24 11:18 UTC, MahmoudBakr23 approved these changes
Hi @isaacpitwa 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Well done making the required changes from the previous reviewer

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 12:14 UTC, merged